contact_links:
  - name: Question and ANswers
    url: https://github.com/discord-php/DiscordPHP/discussions/categories/q-a
    about: If you have question about how to use this Library, please do not make issues, instead go find or create one in Discussions
